pdf: parcial

parcial: relatorio_parcial.tex
	-pdflatex -interaction nonstopmode -shell-escape relatorio_parcial
	-bibtex relatorio_parcial
	-pdflatex -interaction nonstopmode -shell-escape relatorio_parcial
	-pdflatex -interaction nonstopmode -shell-escape relatorio_parcial
